name: macos-homebrew-PR-check
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 

  workflow_dispatch:
  
  pull_request:
    branches:
      - dev
      - master
      - staged
    paths-ignore:
      - 'docs/**'
      # - ".github/**"
      - "howto/**"
      - "*.md"
      - "locale/**"
      - "website/**"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
        qt_ver: [6.5.1]
        qt_arch: [clang_64]
    env:
      targetName: GoldenDict
    steps:

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          
          modules: qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtspeech
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Set outputs
        id: githash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)"    >> $GITHUB_OUTPUT
       
      - name: install deps on macos
        run: |
          brew install cmake ninja
          brew install automake
          brew install autoconf
          brew install libtool
          brew install opencc
          
          brew install libao
          brew install libiconv
          brew install lzo bzip2
          brew install libogg
          brew install zstd lzip
          brew install libvorbis --force
          brew install hunspell
          wget ftp://ftp.sra.co.jp/pub/misc/eb/eb-4.4.3.tar.bz2
          tar xvjf eb-4.4.3.tar.bz2
          cd eb-4.4.3 && ./configure && make -j 8 && sudo make install && cd ..
          brew install  xz lzo 
          brew install pkg-config
          brew install libiconv
          brew install xapian
          brew install libzim

      - name: compile
        run: |          
          qmake CONFIG+=release CONFIG+=no_macos_universal CONFIG+=zim_support CONFIG+=use_iconv CONFIG+=use_xapian  CONFIG+=no_ffmpeg_player
          make 
     
