name: Windows-PR-check
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 

  workflow_dispatch:
      
  pull_request:
    branches:
      - dev
      - master
      - staged
    paths-ignore:
      - 'docs/**'
      # - ".github/**"
      - "howto/**"
      - "*.md"
      - "locale/**"
      - "website/**"

jobs:
  build:
    name: Build
    # see https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        qt_ver: [5.15.2,6.6.0]
        qt_arch: [win64_msvc2019_64]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Qt
        if: ${{ matrix.qt_ver == '5.15.2' }}        
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          
          modules: qtwebengine          
      - name: Install Qt
        if: ${{ matrix.qt_ver != '5.15.2' }}      
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          
          modules: qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats qtspeech
          setup-python: 'false'
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      
      - uses: ilammy/msvc-dev-cmd@v1
        # with:
        #   arch: ${{ matrix.msvc_arch }}    
      - name: msvc-build goldendict
        id: build
        shell: cmd
        run: |
          qmake "CONFIG+=zim_support" CONFIG+=release CONFIG+=use_iconv CONFIG+=use_xapian  CONFIG+=no_ffmpeg_player
          nmake
